package acolyte;

import java.sql.SQLException;
import java.sql.ResultSet;

/**
 * Statement handler: allow to process statement by 'hand' and return.
 *
 * @author Cedric Chantepie
 */
public interface StatementHandler {
    
    /**
     * When given |sql| query is executed against Acolyte connection ...
     *
     * @param sql SQL query
     * @return Query result set
     */
    public ResultSet whenSQLQuery(String sql) throws SQLException;

    /**
     * When given |sql| update is executed against Acolyte connection ...
     *
     * @param sql SQL update statement
     * @return Row count
     */
    public int whenSQLUpdate(String sql) throws SQLException;

    /**
     * If statement is neither a PreparedStatement nor a CallbableStatement,
     * determines whether given |sql| is a query.
     *
     * If returns true, whenSQLQuery will be called.
     */
    public boolean isQuery(String sql);

    /**
     * Returns keys generated by last execution.
     */
    public ResultSet getGeneratedKeys();

} // end of interface StatementHandler
